services:

  ctrl:
    container_name: ctrl
    image: ctrl:0.0.1
    build:
      context: .
      dockerfile: ctrl.Dockerfile
    environment:
      MSG: "ctrl"
      ANSIBLE_USERNAME: ansbl
      ANSIBLE_HOST_KEY_CHECKING: false
    secrets:
      - ansible_pwd
    volumes:
      - ./playbook:/init/playbook

  ubuntu:
    container_name: ubuntu
    image: ubuntu:0.0.1
    build:
      context: .
      dockerfile: ubuntu.Dockerfile
      args:
        ANSIBLE_USERNAME: ansbl
      secrets:
        - ansible_pwd
    environment:
      MSG: "ubuntu"

  centos7:
    container_name: centos7
    image: centos:0.0.1
    build:
      context: .
      dockerfile: centos7.Dockerfile
      args:
        ANSIBLE_USERNAME: ansbl
      secrets:
        - ansible_pwd
    environment:
      MSG: "centos7"

secrets:
  ansible_pwd:
    file: secrets/ansible-pwd.txt
