---

- name: Print OS facts
  tags:
    - test
  hosts: all
  tasks:
    - name: Print OS
      ansible.builtin.debug:
        msg: |
          {{ {
            "OS": "%s %s %s" % (ansible_distribution, ansible_distribution_version, ansible_architecture),
            "External IP": ansible_host,
            "DN": dn
          } }}


- name: Install Clickhouse
  tags:
    - clickhouse
  hosts: clickhouse

  pre_tasks:
    - name: Install common packages
      become: true
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - gpg

  roles:
    - role: clickhouse
      vars:
        clickhouse_listen_host:
          - "::"
        # Uncomment to LightHouse could connect to ClickHouse
        # clickhouse_networks_default:
        #   - "::/0"
        clickhouse_users_custom:
          - name: vector
            password: veve
            networks:
              - "::/0"
            profile: default
            quota: default
            dbs:
              - logs
            comment: User for Vector
        clickhouse_dbs_custom:
          - name: logs

  post_tasks:
    - name: Prepare Clickhouse DB script
      become: true
      ansible.builtin.template:
        src: files/clickhouse/db.sql
        dest: clickhouse-db.sql
        mode: '0664'
    - name: Execute Clickhouse DB script
      ansible.builtin.command: clickhouse-client --queries-file clickhouse-db.sql
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0


- name: Install Vector
  tags:
    - vector
  hosts: vector

  roles:
    - role: vector


- name: Install LightHouse
  tags:
    - lighthouse
  hosts: lighthouse

  roles:
    - role: lighthouse
