{
 "title": "My Dashboard",
 "time": { "from": "2024-10-15T17:33:23.312Z", "to": "2024-10-15T18:03:23.312Z" },
 "panels": [
  {
   "title": "CPU Usage %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"nodeexporter:9100\"}[1m])) * 100)",
     "legendFormat": "Usage %"
    }
   ]
  },
  {
   "title": "CPU LA",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "CPU LA 1" },
    { "expr": "node_load5", "legendFormat": "CPU LA 5" },
    { "expr": "node_load15", "legendFormat": "CPU LA 15" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"nodeexporter:9100\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"nodeexporter:9100\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"}",
     "legendFormat": "Available"
    }
   ]
  }
 ]
}