---
all:
  hosts:
    nexus-01:
      ansible_host: 84.252.141.131
  children:
    nexus:
      hosts:
        nexus-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: admin
    ansible_private_key_file: ../../03/ssh/admin-nopwd
