---
  - name: Print os facts
    hosts: all
    tasks:
      - name: Print OS
        debug:
          msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_architecture }}"
      - name: Print fact
        debug:
          msg: "{{ some_fact }}"