---

- name: Print OS facts
  tags:
    - test
  hosts: all
  tasks:
    - name: Print OS
      debug:
        msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_architecture }}"

- name: Install Clickhouse
  tags:
    - clickhouse
  hosts: clickhouse
  
  tasks:
    - name: Install common packages
      become: true
      ansible.builtin.apt:
        update_cache: yes
        pkg:
          - gpg
    - name: Add Clickhouse apt-key
      become: true
      ansible.builtin.get_url:
        url: https://packages.clickhouse.com/rpm/lts/repodata/repomd.xml.key
        dest: /etc/apt/trusted.gpg.d/clickhouse.asc
        mode: '0644'
        force: true
    - name: Add Clickhouse apt repository
      become: true
      ansible.builtin.apt_repository: 
        update_cache: yes
        repo: deb https://packages.clickhouse.com/deb stable main
        state: present 
        filename: clickhouse 
    - name: Install Clickhouse
      become: true
      ansible.builtin.apt: 
        update_cache: yes
        pkg:
          - clickhouse-server
          - clickhouse-client
        state: present
    - name: Configure Clickhouse
      become: true
      ansible.builtin.template:
        src: files/clickhouse/server.yml
        dest: /etc/clickhouse-server/config.d/server.yml
    - name: Start Clickhouse server
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
    - name: Prepare Clickhouse DB script
      become: true
      ansible.builtin.template:
        src: files/clickhouse/db.sql
        dest: clickhouse-db.sql
    - name: Execute Clickhouse DB script
      ansible.builtin.command: clickhouse-client --queries-file clickhouse-db.sql
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0
