sources:
  filein:
    type: file
    include:
      - /var/vector_input.txt

sinks:
  stdout:
    inputs:
      - filein
    type: console
    encoding:
      codec: text
  fileout:
    inputs:
      - filein
    type: file
    path: /var/vector_output.txt
    encoding:
      codec: text
