---
- name: Add Vector apt repository
  ansible.builtin.shell: bash -c "$(curl -L https://setup.vector.dev)"
  register: result
  changed_when: result.rc == 0
  failed_when: result.rc != 0
- name: Install Vector
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - vector
    state: present
- name: Configure Vector
  become: true
  ansible.builtin.template:
    src: templates/vector.yaml
    dest: /etc/vector/vector.yaml
    mode: '0664'
- name: Create input file
  become: true
  ansible.builtin.file:
    path: /var/vector_input.txt
    state: touch
    owner: vector
    group: vector
    mode: '0666'
- name: Create output file
  become: true
  ansible.builtin.file:
    path: /var/vector_output.txt
    state: touch
    owner: vector
    group: vector
    mode: '0664'
- name: Start Vector
  become: true
  ansible.builtin.service:
    name: vector
    state: restarted
